### PR TITLE
Debian packaging system

### PR DESCRIPTION
**Pull request by kdm9**
Hi Vince,

This Pull Request adds the config files needed to package scythe into Debian. I've got an intent-to-package bug filed, and I've volunteered to be the person responsible for keeping the Debian package up to date with your code.

This means that people will just be able to do an `apt-get install scythe` and they'll have scythe on the Debian boxes.

Theoretically, this would also allow someone to package it for ubuntu, mint or any other apt/dpkg based distros (though I don't have any plans to do so myself).

Cheers,
Kevin

P.S., if you're not happy having this in the main code repo, I'm happy to host just the Debian specific parts in a separate repo, which happens a lot in the world of packaging, from what I can tell.

### CODE REVIEW

**Comment by kdm9** [comment]
Sorry, forgot to mention: this is a work in progress, please don't merge yet! I'll probably have to change the config files once a debian developer reviews my work

**Comment by kdm9** [comment]
The package is now uploaded for sponsorship, review and hopefully eventual acceptance into debian: http://mentors.debian.net/package/scythe

**Comment by vsbuffalo** [comment]
This is terrific, thanks! 

I think a fork might be best, just to keep this repo clean (I moved the paper out of this repo for the same reason). I'm happy to host it if you like. Does that sound good?

**Comment by kdm9** [comment]
OK, sure. I might re-submit some of the changes to the makefile as there are a couple of things that would be required to package with debian (e.g. appending to CFLAGS, not overwriting).

The other option is to use a `debian` branch in the main repo to hold this stuff, and then merge master in to do a release.
See https://wiki.debian.org/PackagingWithGit#Using_the_upstream_repo

**Comment by kdmurray91** [comment]
OK, whatever suits you.

Another option is to keep it in a specific branch, which is one of the recommended ways of packaging [see here](https://wiki.debian.org/PackagingWithGit)

**Comment by kdm9** [comment]
Hi Vince,

Hope this finds you well.

I've made contact with Andreas Tille from Debian Med (which maintains all bioinformatics packages in Debian) about getting scythe into Debian. It is Debian Med policy that the packaging be in a debian-hosted git repo, separate to the source. Therefore I'll close this PR, and will additionally email you about  some further requests they have.

Cheers,
Kevin

**Pull request closed without merging**
