### PR TITLE
Fix the adapter in the matches report.

### PR DESCRIPTION
**Pull request by jarondl**
Saved the current adapter index in best_adapter

### CODE REVIEW

**Comment by jarondl** [comment]
In the matches file, defined by `-m`, all the adapter names were the same. Also, the adapter sequences were the same, leading odd reports such as this:

```
AATGATACGGCGACCACC
|||||||||||||||||
TGGAATTCTCGGGTGCCN
```

After applying this commit, the same run returns:

```
TGGAATTCTCGGGTGCCA
||||||||||||||||| 
TGGAATTCTCGGGTGCCN
```

**Comment by jarondl** [comment]
Hi @vsbuffalo ,
any comments about this pull request?

**Comment by vsbuffalo** [comment]
Oh, sorry! I've been terribly busy. I'll try to take take a look this week.
Thanks!!

On Mon, Dec 16, 2013 at 1:55 AM, jarondl notifications@github.com wrote:

> Hi @vsbuffalo https://github.com/vsbuffalo ,
> any comments about this pull request?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/vsbuffalo/scythe/pull/13#issuecomment-30648043
> .

## 

Vince Buffalo
Ross-Ibarra Lab (www.rilab.org)
Plant Sciences, UC Davis

**Comment by jarondl** [comment]
That's great, thank you.
Note that it is only one added row, nothing complicated.

**Pull request merged**
